# Generated by Django 4.0.3 on 2022-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_rename_name_binvo_closet_name_binvo_bin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='bin_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
